/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/file.gltf --transform 
Files: ./public/models/file.gltf [743.31KB] > /home/yu23ki14/apps/senspace/gacha/frontend/file-transformed.glb [80.79KB] (89%)
*/

import React, { FC, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Model: FC = (props) => {
  const { nodes, materials } = useGLTF('/models/file-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.kaedim_mesh_0 as any).geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={(nodes.kaedim_mesh_1 as any).geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={(nodes.kaedim_mesh_2 as any).geometry}
        material={materials.PaletteMaterial002}
      />
    </group>
  )
}

useGLTF.preload('/models/file-transformed.glb')

export default Model
