import {
  Container,
  Heading,
  ListItem,
  Text,
  UnorderedList,
} from '@chakra-ui/layout'
import { NextPage } from 'next'
import Link from 'next/link'

const Rules: NextPage = () => {
  return (
    <Container color="yellow.400" maxW="xl" mb={10} fontSize="sm">
      <Heading
        textAlign="center"
        fontFamily="stolzl, sans-serif"
        fontWeight={500}
        mt={5}
        mb={8}
        fontSize="4xl"
      >
        Rules
      </Heading>

      <Text mb={6}>
      “The Ball” $CRASH Edition is an exclusive collab version of What’s in the Ball? with 747air.
      </Text>

      <Text mb={3}>Draw NFTs from “The Ball” and get $HIGHBALL!</Text>
      <UnorderedList mb={6}>
        <ListItem>Common NFT = 200 $HIGHBALL</ListItem>
        <ListItem>Rare NFT = 400 $HIGHBALL</ListItem>
        <ListItem>Special NFT = 800 $HIGHBALL</ListItem>
      </UnorderedList>

      <Text mb={6}>
        $HIGHBALL are centralized, offchain points though a decentralized token may
        be issued at a later date.
      </Text>

      <Text mb={3}>Your $HIGHBALL</Text>
      <UnorderedList mb={6}>
        <ListItem>Probability of winning prize pool</ListItem>
        <ListItem>Eligibility for exclusive NFT Drops, High Miles, and more TBD</ListItem>
      </UnorderedList>

      <Text mb={3}>Prize Pool</Text>
      <UnorderedList mb={6}>
        <ListItem>
        Created from NFT sales generated by minting NFTs from airport.theball.fun and IRL credits at FarCon
        </ListItem>
        <ListItem>
          Any NFTs drawn after game period ends will not count towards next round
        </ListItem>
        <ListItem>
        Winner to be selected at random using <a href="https://github.com/senspace-studio/theball-lottery">same methodology as Season 1</a>
        </ListItem>
        <ListItem>
          $BALL leaderboard (including $BALL generated to date) will go live
          shortly
        </ListItem>
      </UnorderedList>

      <Text mb={3}>Prize Pool Split</Text>
      <UnorderedList mb={6}>
        <ListItem>72% First place</ListItem>
        <ListItem>9% Second place (two winners)</ListItem>
        <ListItem>5% to $CRASH LP</ListItem>
        <ListItem>5% to Senspace</ListItem>
      </UnorderedList>

      <Text mb={6}>
        It is very unlikely that you will win the prize pool and you should not play the game for that purpose. The “What’s in the Ball” project is made for entertainment purposes only and you should play for fun.
      </Text>

      <Text>
        The “What’s in the Ball” team reserves the right to change the rules of
        the game at any time, but we will do our very best not to rug you!
      </Text>
    </Container>
  )
}

export default Rules
