import {
  Container,
  Heading,
  ListItem,
  Text,
  UnorderedList,
} from '@chakra-ui/layout'
import { NextPage } from 'next'
import Link from 'next/link'

const Rules: NextPage = () => {
  return (
    <Container color="yellow.400" maxW="xl" mb={10} fontSize="sm">
      <Heading
        textAlign="center"
        fontFamily="stolzl, sans-serif"
        fontWeight={500}
        mt={5}
        mb={8}
        fontSize="4xl"
      >
        Rules
      </Heading>

      <Text mb={6}>
        Introducing “The Ball,” a magical digital capsule toy machine from
        Tokyo.
      </Text>

      <Text mb={3}>Draw NFTs from “The Ball” and get $BALL!</Text>
      <UnorderedList mb={6}>
        <ListItem>Common NFT = 200 $BALL</ListItem>
        <ListItem>Rare NFT = 400 $BALL</ListItem>
        <ListItem>Special NFT = 800 $BALL</ListItem>
      </UnorderedList>

      <Text mb={6}>
        $BALL are centralized, offchain points though a decentralized token may
        be issued at a later date.
      </Text>

      <Text mb={3}>Your $BALL</Text>
      <UnorderedList mb={6}>
        <ListItem>Probability of winning prize pool</ListItem>
        <ListItem>Eligibility for exclusive NFT Drops</ListItem>
        <ListItem>Other perks (TBA)</ListItem>
      </UnorderedList>

      <Text mb={3}>Prize Pool</Text>
      <UnorderedList mb={6}>
        <ListItem>
          Created from protocol rewards generated by minting NFTs from “The
          Ball” and other official NFTs
        </ListItem>
        <ListItem>
          Any NFTs drawn after game period ends will count towards next round
        </ListItem>
        <ListItem>
          First round of “The Ball” and the length of the round TBA
        </ListItem>
        <ListItem>
          Winner to be selected at random (methodology to be made public)
        </ListItem>
        <ListItem>
          $BALL leaderboard (including $BALL generated to date) will go live
          shortly
        </ListItem>
      </UnorderedList>

      <Text mb={3}>Prize Pool Split</Text>
      <UnorderedList mb={6}>
        <ListItem>72% First place</ListItem>
        <ListItem>9% Second place (two winners)</ListItem>
        <ListItem>5% to next round prize pool</ListItem>
        <ListItem>5% to operating team</ListItem>
      </UnorderedList>

      <Text mb={3}>Other ways to get $BALL</Text>
      <UnorderedList mb={6}>
        <ListItem>Mint official NFTs = 200 $BALL</ListItem>
        <ListItem>
          Approved art in What’s in the Ball Friends and Family Collection
          (submit via DM @renstern.eth on Warpcast) = 30 randomly picked NFTs
        </ListItem>
        <ListItem>“Double points” times to be announced periodically</ListItem>
        <ListItem>Additional tasks TBA</ListItem>
      </UnorderedList>

      <Text mb={1} textDecor="underline">
        <Link
          target="_blank"
          href="https://gallery.so/WhatsintheBall/galleries/2eAttlJbvtV3XK41Y4ys103qsUW"
        >
          Official NFT List
        </Link>
      </Text>
      <Text mb={6} textDecor="underline">
        <Link
          target="_blank"
          href="https://drive.google.com/drive/folders/1cF1POI3XiuPB5sqGyvL_KIO08o8lQQ0d?usp=sharing"
        >
          What’s in the Ball? Brand Assets
        </Link>
      </Text>

      <Text mb={6}>
        The “What’s in the Ball” project is made for entertainment purposes
        only.
      </Text>

      <Text>
        The “What’s in the Ball” team reserves the right to change the rules of
        the game at any time, but we will do our very best not to rug you!
      </Text>
    </Container>
  )
}

export default Rules
